# 服务端口
server:
  port: 8006

spring:
  application:
    name: cow-interface

  # 注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/b2b_server?serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    tomcat:
      max-wait: 10000
      max-active: 30
      test-on-borrow: true

  # json全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:com/cow/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false

